steps:
- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: ESRP Sign binaries
  inputs:
    ConnectedServiceName: 'ESRP CodeSigning VSTS'
    FolderPath: $(projectDirectory)/.oml/package
    Pattern: '*.dll,*.exe'
    signConfigType: inlineSignParams
    inlineOperation: |
      [
          {
              "KeyCode" : "CP-230856",
              "OperationCode" : "SigntoolSign",
              "Parameters" : {
                  "OpusName" : "Microsoft",
                  "OpusInfo" : "http://www.microsoft.com",
                  "PageHash" : "/NPH",
                  "TimeStamp" : "/t \"http://ts2048.gtm.microsoft.com/TSS/AuthenticodeTS\""
              },
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          },
          {
              "KeyCode" : "CP-230856",
              "OperationCode" : "SigntoolVerify",
              "Parameters" : {},
              "ToolName" : "sign",
              "ToolVersion" : "1.0"
          }
      ]

- script: |
    call activate $(projectName)
    oml dlis manifest
  displayName: Create Manifest
  workingDirectory: $(projectDirectory)/.oml/

- task: SFP.build-tasks.custom-build-task-1.EsrpCodeSigning@1
  displayName: ESRP CodeSigning JSON Manifest
  inputs:
    ConnectedServiceName: ESRP CodeSigning VSTS
    FolderPath: $(projectDirectory)/.oml/package
    Pattern: SecureManifest.json
    signConfigType: inlineSignParams
    inlineOperation: |
     [
         {
             "keyCode": "CP-230012",
             "operationSetCode": "JsonSign",
             "parameters": [],
             "toolName": "sign",
             "toolVersion": "1.0"
         }
     ]
